-- changeset sergiovqc:1744889844767-1

CREATE TABLE CATEGORIAS (CATEGORIA_ID NUMBER(38) AUTOINCREMENT (1, 1) NOT NULL, NOMBRE VARCHAR(100) NOT NULL, DESCRIPCION VARCHAR(1000), CONSTRAINT PK_CATEGORIAS PRIMARY KEY (CATEGORIA_ID));


-- changeset sergiovqc:1744889844767-2

CREATE TABLE CLIENTES (CLIENTE_ID NUMBER(38) AUTOINCREMENT (1, 1) NOT NULL, NOMBRE VARCHAR(150) NOT NULL, EMAIL VARCHAR(150) NOT NULL, TELEFONO VARCHAR(20), FECHA_REGISTRO date DEFAULT CURRENT_DATE(), CONSTRAINT PK_CLIENTES PRIMARY KEY (CLIENTE_ID));


-- changeset sergiovqc:1744889844767-6

ALTER TABLE CLIENTES ADD CONSTRAINT UQ_CLIENTES_EMAIL UNIQUE (EMAIL);


-- changeset sergiovqc:1744889844767-3

CREATE TABLE DETALLE_PEDIDOS (DETALLE_ID NUMBER(38) AUTOINCREMENT (1, 1) NOT NULL, PEDIDO_ID NUMBER(38) NOT NULL, PRODUCTO_ID NUMBER(38) NOT NULL, CANTIDAD NUMBER(38) DEFAULT 1, PRECIO_UNITARIO NUMBER(10, 2) NOT NULL, SUBTOTAL NUMBER(12, 2), CONSTRAINT PK_DETALLE_PEDIDOS PRIMARY KEY (DETALLE_ID));


-- changeset sergiovqc:1744889844767-4

CREATE TABLE PEDIDOS (PEDIDO_ID NUMBER(38) AUTOINCREMENT (1, 1) NOT NULL, CLIENTE_ID NUMBER(38) NOT NULL, FECHA_PEDIDO TIMESTAMPLTZ(9) DEFAULT 'CURRENT_TIMESTAMP()', TOTAL NUMBER(12, 2) DEFAULT 0 NOT NULL, ESTADO_PEDIDO VARCHAR(20) DEFAULT 'pendiente' NOT NULL, FECHA_ENVIO date, CONSTRAINT PK_PEDIDOS PRIMARY KEY (PEDIDO_ID));


-- changeset sergiovqc:1744889844767-7

ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (CLIENTE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;


-- changeset sergiovqc:1744889844767-5

CREATE TABLE PRODUCTOS (PRODUCTO_ID NUMBER(38) AUTOINCREMENT (1, 1) NOT NULL, NOMBRE VARCHAR(150) NOT NULL, DESCRIPCION VARCHAR(1000), PRECIO NUMBER(10, 2) DEFAULT 0 NOT NULL, STOCK NUMBER(38) DEFAULT 0 NOT NULL, CATEGORIA_ID NUMBER(38), CONSTRAINT PK_PRODUCTOS PRIMARY KEY (PRODUCTO_ID));


-- changeset sergiovqc:1744889844767-8

ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_PRODUCTOS_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS (CATEGORIA_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;


-- changeset sergiovqc:1744889844767-9

DROP TABLE JUGADORES;


